### ISSUE TITLE
Perfect idea

### ISSUE THREAD

**Issue by cagataycali** [qua-ve/useraccounts-framework7#1]
Perfect idea but isn't working properly.

**Comment by filipenevola** [comment]
@ccali14 what is the problem?

**Comment by cagataycali** [comment]
When I install, the ui doesn't changed then I try to change my useraccounts-ui unstyled then try install again but nothing changed? There is any doc for installing?

**Comment by filipenevola** [comment]
You need to add any package with framework7 style.

I use this one: nobutakaoshiro:framework7-ios-material

Are you using what package?

If you still with problems please paste your code here.

Follows the complete guide about useraccounts core https://github.com/meteor-useraccounts/core/blob/master/Guide.md
